image: node:lts

stages:
  - test

before_script:
  - yarn install

mocha:
  stage: test
  allow_failure: false
  script:
    - yarn run test

coverage:
  stage: test
  allow_failure: true
  script:
    - yarn run coverage

eslint:
  stage: test
  allow_failure: true
  script:
    - yarn run lint