image: node:lts

stages:
  - test

before_script:
  - yarn install

job 0:
  stage: test
  allow_failure: false
  script:
    - yarn run test

job 1:
  stage: test
  allow_failure: true
  script:
    - yarn run coverage

job 2:
  stage: test
  allow_failure: true
  script:
    - yarn run lint